categories = {
    "media": {
        description: "Social Media Accounts"
    },
    "website": {
        description: "Websites of Information"
    },
    "people": {
        description: "Interesting people"
    },
    "tools": {
        description: "Tools on desktop/mobile"
    },
    "chats": {
        description: "Join the daily discussions"
    },
    "docs": {
        description: "Code and Libraries"
    },
    "code": {
        description: "Open source projects"
    }
}

items = [
    {
        "url": "https://medium.com/@vechainofficial",
        "category": "media",
        "platform": "medium",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": "vechainofficial",
        "personal_account": false,
        "editor_comments": "Official account, updates once there are business news on Vechain.",
        "editor_title": "VeChain Medium",
        "editor_languages": ["english"]
    },
    {
        "url": "https://twitter.com/vechainofficial",
        "category": "media",
        "platform": "twitter",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": "vechainofficial",
        "personal_account": false,
        "editor_comments": "Official account on Twitter.",
        "editor_title": "VeChain Twitter",
        "editor_languages": ["english"]
    },
    {
        "url": "https://twitter.com/vechaindev",
        "category": "media",
        "platform": "twitter",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": "vechaindev",
        "personal_account": false,
        "editor_comments": "Developer related news, updates new technology advancements, tutorials, and milestone releases.",
        "editor_title": "VeChainDev Twitter",
        "editor_languages": ["english"]
    },

    {
        "url": "https://weibo.com/u/6353774918",
        "category": "media",
        "platform": "weibo",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": "6353774918",
        "personal_account": false,
        "editor_title": "VeChain Weibo",
        "editor_comments": "The VeChain Foundation channel on Weibo in Chinese language.",
        "editor_languages": ["chinese"]
    },
    {
        "url": "https://weibo.com/u/6306565418",
        "category": "media",
        "platform": "weibo",
        "run_by_official": false,
        "organization": true,
        "platform_identifier": "6306565418",
        "personal_account": false,
        "editor_title": "VeChain Fans Weibo",
        "editor_comments": "VeChain Fans on Weibo, in Chinese language.",
        "editor_languages": ["chinese"]
    },
    {
        "url": "https://twitter.com/VeChainStats",
        "category": "media",
        "platform": "twitter",
        "run_by_official": false,
        "organization": true,
        "platform_identifier": "VeChainStats Twitter",
        "personal_account": false,
        "editor_title": "Vechainstats",
        "editor_comments": "Announcements of vechainstats.com, a powerful community block explorer made by Fabian.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://vechain101.com/",
        "category": "website",
        "platform": "website",
        "run_by_official": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain101.com",
        "editor_comments": "VeChain news and advancements from community editors.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://twitter.com/vechainthorscan",
        "category": "media",
        "platform": "twitter",
        "run_by_official": false,
        "organization": true,
        "platform_identifier": "vechainthorscan",
        "personal_account": false,
        "editor_title": "VechainThorScan",
        "editor_comments": "Announcements of a community VeChain explorer with an elegant UI.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://twitter.com/sunshinelu24",
        "category": "people",
        "platform": "twitter",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "sunshinelu24",
        "personal_account": true,
        "editor_title": "Sunny",
        "editor_comments": "CEO of VeChain.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://twitter.com/kfeng027",
        "category": "people",
        "platform": "twitter",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "kfeng027",
        "personal_account": true,
        "editor_title": "Kevin",
        "editor_comments": "COO of VeChain.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://twitter.com/qian_bin_cola_t",
        "category": "people",
        "platform": "twitter",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "qian_bin_cola_t",
        "personal_account": true,
        "editor_title": "Qian Bin",
        "editor_comments": "Core dev of VeChainThor Blockchain.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://twitter.com/BenYorke",
        "category": "people",
        "platform": "twitter",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "BenYorke",
        "personal_account": true,
        "editor_title": "Ben Yorke",
        "editor_comments": "Ben York, VeChain101's editor, blockchain enthusiast.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://twitter.com/liboliqi",
        "category": "people",
        "platform": "twitter",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "liboliqi",
        "personal_account": true,
        "editor_title": "Tony",
        "editor_comments": "Core dev of VeChainThor Blockchain.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://twitter.com/tahpot",
        "category": "people",
        "platform": "twitter",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "tahpot",
        "personal_account": true,
        "editor_title": "Chris",
        "editor_comments": "Founder of Verida.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://twitter.com/PeterZh47977516",
        "category": "people",
        "platform": "twitter",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "PeterZh47977516",
        "personal_account": true,
        "editor_title": "Dr. Peter Zhou",
        "editor_comments": "VeChain Scientist.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://twitter.com/abyteahead",
        "category": "people",
        "platform": "twitter",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "abyteahead",
        "personal_account": true,
        "editor_title": "A Byte Ahead",
        "editor_comments": "He writes VeChain tutorials and apps.",
        "editor_languages": ["english"]
    },
    
    {
        "url": "https://www.reddit.com/r/Vechain/",
        "category": "chats",
        "platform": "reddit",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": "Vechain",
        "personal_account": false,
        "editor_title": "VeChain Reddit",
        "editor_comments": "General discussion channel on Reddit.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://explore.vechain.org/",
        "category": "tools",
        "platform": "website",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Explorer",
        "editor_comments": "Fast and reliable VeChain official explorer.",
        "editor_languages": ["english"]
    },
    {
        "url": "http://vestats.com/",
        "category": "tools",
        "platform": "website",
        "run_by_official": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VechainStats",
        "editor_comments": "Community VeChain explorer with rich functionalities.",
        "editor_languages": ["english", "chinese", ""]
    },
    {
        "url": "https://vechainthorscan.com/",
        "category": "tools",
        "platform": "website",
        "run_by_official": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VechainThorScan",
        "editor_comments": "Community VeChain explorer with an elegant UI.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://vechaininsider.com/",
        "category": "website",
        "platform": "website",
        "run_by_official": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Insider",
        "editor_comments": "Community run VeChain News.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://t.me/VeChainDevCommunity",
        "category": "chats",
        "platform": "telegram",
        "run_by_official": false,
        "organization": true,
        "platform_identifier": "VeChainDevCommunity",
        "personal_account": false,
        "editor_title": "Developers' Chat",
        "editor_comments": "Huge community developers' chat on coding. Go make some friends there!",
        "editor_languages": ["english"]
    },
    {
        "url": "https://t.me/vechain_official_CN",
        "category": "chats",
        "platform": "telegram",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": "vechain_official_CN",
        "personal_account": false,
        "editor_title": "Chinese Telegram",
        "editor_comments": "Traders, announcements and price discussions in Chinese.",
        "editor_languages": ["chinese"]
    },
    {
        "url": "https://t.me/vechain_official_en",
        "category": "chats",
        "platform": "telegram",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": "vechain_official_en",
        "personal_account": false,
        "editor_title": "English Telegram",
        "editor_comments": "Traders, announcements and price discussions in English.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://t.me/vechainthorscan",
        "category": "chats",
        "platform": "telegram",
        "run_by_official": false,
        "organization": true,
        "platform_identifier": "vechainthorscan",
        "personal_account": false,
        "editor_title": "Vechainthorscan Devs",
        "editor_comments": "Developers' discussion, bug fix, feature request of vechainthorscan.com",
        "editor_languages": ["english"]
    },
    {
        "url": "https://t.me/vechainwallet",
        "category": "chats",
        "platform": "telegram",
        "run_by_official": false,
        "organization": true,
        "platform_identifier": "vechainwallet",
        "personal_account": false,
        "editor_title": "Community Browser Extension",
        "editor_comments": "Discussion of a newly made Chrome browser wallet extension.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://github.com/vechain/",
        "category": "code",
        "platform": "github",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": "vechain",
        "personal_account": false,
        "editor_title": "VeChain Github",
        "editor_comments": "Main Source code of VeChain blockchain, tools, and libraries.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://github.com/vechain/thor-devkit.js",
        "category": "code",
        "platform": "github",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": "vechain",
        "personal_account": false,
        "editor_title": "Thor Devkit",
        "editor_comments": "JavaScript SDK library. Wallets generation, transactions assembling.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://github.com/vechain/token-registry",
        "category": "code",
        "platform": "github",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Token Registry",
        "editor_comments": "Tokens reside on VeChain. You can submit one by pull request.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://github.com/vechain/app-hub",
        "category": "code",
        "platform": "github",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "App Hub",
        "editor_comments": "3rd party dApps appears in Sync. You can submit one by pull request.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://apps.apple.com/fi/app/vechainthor/id1397679485",
        "category": "tools",
        "platform": "mobile",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "iPhone Wallet",
        "editor_comments": "Official mobile wallet to transfer funds, view dApps.",
        "editor_languages": ["english", "chinese"]
    },
    {
        "url": "https://play.google.com/store/apps/details?id=com.vechain.wallet",
        "category": "tools",
        "platform": "mobile",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Android Wallet",
        "editor_comments": "Official mobile wallet to transfer funds, view dApps.",
        "editor_languages": ["english", "chinese"]
    },
    {
        "url": "https://apps.apple.com/fi/app/vechain-pro/id1335906787",
        "category": "tools",
        "platform": "mobile",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Pro iOS",
        "editor_comments": "Client-side ToolChain Scanner.",
        "editor_languages": ["english", "chinese"]
    },
    {
        "url": "https://play.google.com/store/apps/details?id=com.vechain.user",
        "category": "tools",
        "platform": "mobile",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Pro Android",
        "editor_comments": "Client-side ToolChain Scanner.",
        "editor_languages": ["english", "chinese"]
    },
    {
        "url": "https://github.com/vechain/thor-sync.electron",
        "category": "tools",
        "platform": "desktop",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Sync",
        "editor_comments": "Desktop wallet to transfer funds, view dApps. (Mac, Windows, Linux)",
        "editor_languages": ["english"]
    },
    {
        "url": "https://chrome.google.com/webstore/detail/vechain-price-checker/ojopeinoooepnfnmifmmjebccpnjamea",
        "category": "tools",
        "platform": "desktop",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Price Checker Extension",
        "editor_comments": "Browser extension to view price quickly.  (Chrome, Firefox)",
        "editor_languages": ["english", "chinese"]
    },
    {
        "url": "https://docs.vechain.org/",
        "category": "docs",
        "platform": "website",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Documentation Center",
        "editor_comments": "Developer resources for docs, tutorials and knowledge.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://connex.vecha.in/#/",
        "category": "docs",
        "platform": "website",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Connex",
        "editor_comments": "Connex API documentation. The standard way to connect to VeChain network.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://github.com/vechain/vips/",
        "category": "docs",
        "platform": "github",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VIPs",
        "editor_comments": "\"VeChain Improvement Proposals\", where new milestones are planned and discussed.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://medium.com/@abyteahead/",
        "category": "docs",
        "platform": "medium",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "abyteahead",
        "personal_account": true,
        "editor_title": "A Byte Ahead Medium",
        "editor_comments": "Tutorials on building apps on VeChain. Explains new features and how-to.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://bbs.vechainworld.io/",
        "category": "chats",
        "platform": "website",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Discussion Forum",
        "editor_comments": "Announcements, AMA sessions and new developments.",
        "editor_languages": ["english", "chinese"]
    },
    {
        "url": "https://www.vechain.org/foundation-grant/",
        "category": "website",
        "platform": "website",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Grant",
        "editor_comments": "Grants to support small start-ups on VeChain.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://www.vechain.org/bounty-program/",
        "category": "website",
        "platform": "website",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Bounty",
        "editor_comments": "Earn money by building tools for VeChain Foundation!",
        "editor_languages": ["english"]
    },
    {
        "url": "https://apps.vechain.org/",
        "category": "website",
        "platform": "website",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Dapps Category",
        "editor_comments": "Find interesting 3rd party apps running on VeChain Blockchain.",
        "editor_languages": ["english"]
    },
    {
        "url": "https://vechain.com/",
        "category": "website",
        "platform": "website",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Vechain.com",
        "editor_comments": "Official website of VeChain as a company. Includes news and collaborations.",
        "editor_languages": ["english", "chinese"]
    },
    {
        "url": "https://vechain.org/",
        "category": "website",
        "platform": "website",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain.org",
        "editor_comments": "Official website of VeChain as a foundation. Includes bounty/grant and technology advancements.",
        "editor_languages": ["english", "chinese"]
    }
]