categories = {
    "media": {
        display: "Media",
        description: "Official media accounts"
    },
    "website": {
        display: "Websites",
        description: "Information hubs related to VeChain"
    },
    "people": {
        display: "People",
        description: "Other account to follow"
    },
    "tools": {
        display: "Tools",
        description: "Tools on desktop/mobile"
    },
    "chats": {
        display: "Chats",
        description: "Join the discussions"
    },
    "docs": {
        display: "Documentations",
        description: "Code and Libraries"
    },
    "code": {
        display: "Code & SDK",
        description: "Open source projects"
    }
}

items = [
    {
        "url": "https://medium.com/@vechainofficial",
        "category": "media",
        "platform": "medium",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": "vechainofficial",
        "personal_account": false,
        "editor_comments": "Official account with important updates from the Vechain Foundation.",
        "editor_title": "VeChain Medium",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://twitter.com/vechainofficial",
        "category": "media",
        "platform": "twitter",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": "vechainofficial",
        "personal_account": false,
        "editor_comments": "Official VeChain Twitter account.",
        "editor_title": "VeChain Twitter",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://twitter.com/vechaindev",
        "category": "media",
        "platform": "twitter",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": "vechaindev",
        "personal_account": false,
        "editor_comments": "Developer related news, updates on new technology advancements, tutorials, and milestone releases.",
        "editor_title": "VeChainDev Twitter",
        "editor_languages": ["english"],
        "job_status":"vechain_team"
    },

    {
        "url": "https://weibo.com/u/6353774918",
        "category": "media",
        "platform": "weibo",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": "6353774918",
        "personal_account": false,
        "editor_title": "VeChain Weibo",
        "editor_comments": "The Chinese language VeChain Foundation channel on Weibo.",
        "editor_languages": ["chinese"],
        "job_status":null
    },
    {
        "url": "https://weibo.com/u/6306565418",
        "category": "media",
        "platform": "weibo",
        "run_by_official": false,
        "organization": true,
        "platform_identifier": "6306565418",
        "personal_account": false,
        "editor_title": "VeChain Fans Weibo",
        "editor_comments": "Chinese language Fan account on Weibo.",
        "editor_languages": ["chinese"],
        "job_status":"community_member"
    },
    {
        "url": "https://twitter.com/VeChainStats",
        "category": "media",
        "platform": "twitter",
        "run_by_official": false,
        "organization": true,
        "platform_identifier": "VeChainStats Twitter",
        "personal_account": false,
        "editor_title": "Vechainstats",
        "editor_comments": "Updates from VeChainStats.com, a powerful community block explorer and analytics tool.",
        "editor_languages": ["english"],
        "job_status":"community_member"
    },
    {
        "url": "https://vechain101.com/",
        "category": "website",
        "platform": "website",
        "run_by_official": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain101.com",
        "editor_comments": "Unofficial news and analysis from community editors.",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://twitter.com/vechainthorscan",
        "category": "media",
        "platform": "twitter",
        "run_by_official": false,
        "organization": true,
        "platform_identifier": "vechainthorscan",
        "personal_account": false,
        "editor_title": "VechainThorScan",
        "editor_comments": "Updates from a community VeChain explorer with an elegant UI.",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://twitter.com/sunshinelu24",
        "category": "people",
        "platform": "twitter",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "sunshinelu24",
        "personal_account": true,
        "editor_title": "Sunny",
        "editor_comments": "CEO of VeChain.",
        "editor_languages": ["english"],
        "job_status":"vechain_team"
    },
    {
        "url": "https://twitter.com/kfeng027",
        "category": "people",
        "platform": "twitter",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "kfeng027",
        "personal_account": true,
        "editor_title": "Kevin",
        "editor_comments": "COO of VeChain.",
        "editor_languages": ["english"],
        "job_status":"vechain_team"
    },
    {
        "url": "https://twitter.com/qian_bin_cola_t",
        "category": "people",
        "platform": "twitter",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "qian_bin_cola_t",
        "personal_account": true,
        "editor_title": "Qian Bin",
        "editor_comments": "Core VeChainThor blockchain dev.",
        "editor_languages": ["english"],
        "job_status":"vechain_team"
    },
    {
        "url": "https://twitter.com/BenYorke",
        "category": "people",
        "platform": "twitter",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "BenYorke",
        "personal_account": true,
        "editor_title": "Ben Yorke",
        "editor_comments": "Editor of VeChain101, and Analyst of Cointelegraph Consulting.",
        "editor_languages": ["english"],
        "job_status":"community_member"
    },
    {
        "url": "https://twitter.com/liboliqi",
        "category": "people",
        "platform": "twitter",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "liboliqi",
        "personal_account": true,
        "editor_title": "Tony",
        "editor_comments": "Core VeChainThor blockchain dev.",
        "editor_languages": ["english"],
        "job_status":"vechain_team"
    },
    {
        "url": "https://twitter.com/tahpot",
        "category": "people",
        "platform": "twitter",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "tahpot",
        "personal_account": true,
        "editor_title": "Chris",
        "editor_comments": "Founder of Verida.",
        "editor_languages": ["english"],
        "job_status":"community_member"
    },    
    {
        "url": "https://twitter.com/Sarah_Nabaa",
        "category": "people",
        "platform": "twitter",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "Sarah_Nabaa",
        "personal_account": true,
        "editor_title": "Sarah Nabaa",
        "editor_comments": "Head of VeChain Southeast Asia & Australia.",
        "editor_languages": ["english"],
        "job_status":"vechain_team"
    },
    {
        "url": "https://twitter.com/jasonrockwood",
        "category": "people",
        "platform": "twitter",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "jasonrockwood",
        "personal_account": true,
        "editor_title": "Jason Rockwood",
        "editor_comments": "Head of VeChain North America.",
        "editor_languages": ["english"],
        "job_status":"vechain_team"
    },
    {
        "url": "https://twitter.com/rgrottola",
        "category": "people",
        "platform": "twitter",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "rgrottola",
        "personal_account": true,
        "editor_title": "Renato Grottola",
        "editor_comments": "DNV GL's Global Head of Digital Assurance and Supply Chain, VeChain Steering Community Member.",
        "editor_languages": ["english"],
        "job_status":"third_party"
    },
    {
        "url": "https://twitter.com/PeterZh47977516",
        "category": "people",
        "platform": "twitter",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "PeterZh47977516",
        "personal_account": true,
        "editor_title": "Dr. Peter Zhou",
        "editor_comments": "VeChain Chief Scientist.",
        "editor_languages": ["english"],
        "job_status":"vechain_team"     
    },
    {
        "url": "https://twitter.com/abyteahead",
        "category": "people",
        "platform": "twitter",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "abyteahead",
        "personal_account": true,
        "editor_title": "A Byte Ahead",
        "editor_comments": "Writer of VeChain tutorials and apps.",
        "editor_languages": ["english"],
        "job_status":"vechain_team"
    },
    {
        "url": "https://twitter.com/MiRei83_",
        "category": "people",
        "platform": "twitter",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "MiRei83_",
        "personal_account": true,
        "editor_title": "Mirei",
        "editor_comments": "Community Dev and founder of VeBlocks.net.",
        "editor_languages": ["english"],
        "job_status":"community_member"
    },    
    {
        "url": "https://www.reddit.com/r/Vechain/",
        "category": "chats",
        "platform": "reddit",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": "Vechain",
        "personal_account": false,
        "editor_title": "VeChain Reddit",
        "editor_comments": "General discussion channel on Reddit.",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://explore.vechain.org/",
        "category": "tools",
        "platform": "website",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Explorer",
        "editor_comments": "Fast and reliable VeChain official block explorer.",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "http://vestats.com/",
        "category": "tools",
        "platform": "website",
        "run_by_official": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VechainStats",
        "editor_comments": "Community VeChain explorer with rich functionalities.",
        "editor_languages": ["english", "chinese", ""],
        "job_status":null
    },
    {
        "url": "https://vechainthorscan.com/",
        "category": "tools",
        "platform": "website",
        "run_by_official": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VechainThorScan",
        "editor_comments": "Community VeChain explorer with an elegant UI.",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://vechaininsider.com/",
        "category": "website",
        "platform": "website",
        "run_by_official": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Insider",
        "editor_comments": "Community run VeChain News.",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://t.me/VeChainDevCommunity",
        "category": "chats",
        "platform": "telegram",
        "run_by_official": false,
        "organization": true,
        "platform_identifier": "VeChainDevCommunity",
        "personal_account": false,
        "editor_title": "Developers' Chat",
        "editor_comments": "Huge community developers' chat on coding. Go make some friends there!",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://t.me/vechain_official_CN",
        "category": "chats",
        "platform": "telegram",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": "vechain_official_CN",
        "personal_account": false,
        "editor_title": "Chinese Telegram",
        "editor_comments": "Traders, announcements and price discussions in Chinese.",
        "editor_languages": ["chinese"],
        "job_status":null
    },
    {
        "url": "https://t.me/vechain_official_en",
        "category": "chats",
        "platform": "telegram",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": "vechain_official_en",
        "personal_account": false,
        "editor_title": "English Telegram",
        "editor_comments": "Traders, announcements and price discussions in English.",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://t.me/vechainthorscan",
        "category": "chats",
        "platform": "telegram",
        "run_by_official": false,
        "organization": true,
        "platform_identifier": "vechainthorscan",
        "personal_account": false,
        "editor_title": "Vechainthorscan Devs",
        "editor_comments": "Developers' discussion, bug fix, feature request of vechainthorscan.com",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://t.me/vechainwallet",
        "category": "chats",
        "platform": "telegram",
        "run_by_official": false,
        "organization": true,
        "platform_identifier": "vechainwallet",
        "personal_account": false,
        "editor_title": "Community Browser Extension",
        "editor_comments": "Discussion of a newly made Chrome browser wallet extension.",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://github.com/vechain/",
        "category": "code",
        "platform": "github",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": "vechain",
        "personal_account": false,
        "editor_title": "VeChain Github",
        "editor_comments": "Main Source code of VeChain blockchain, tools, and libraries.",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://github.com/vechain/thor-devkit.js",
        "category": "code",
        "platform": "github",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": "vechain",
        "personal_account": false,
        "editor_title": "Thor Devkit",
        "editor_comments": "JavaScript SDK library. Wallets generation, transaction assembling.",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://github.com/vechain/token-registry",
        "category": "code",
        "platform": "github",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Token Registry",
        "editor_comments": "Tokens residing on VeChain. You can submit one by pull request.",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://github.com/vechain/app-hub",
        "category": "code",
        "platform": "github",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "App Hub",
        "editor_comments": "3rd party dApps appearing in Sync. You can submit one by pull request.",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://apps.apple.com/fi/app/vechainthor/id1397679485",
        "category": "tools",
        "platform": "mobile",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "iPhone Wallet",
        "editor_comments": "Official mobile wallet and dApp browser.",
        "editor_languages": ["english", "chinese"],
        "job_status":null
    },
    {
        "url": "https://play.google.com/store/apps/details?id=com.vechain.wallet",
        "category": "tools",
        "platform": "mobile",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Android Wallet",
        "editor_comments": "Official mobile wallet and dApp browser.",
        "editor_languages": ["english", "chinese"],
        "job_status":null
    },
    {
        "url": "https://apps.apple.com/fi/app/vechain-pro/id1335906787",
        "category": "tools",
        "platform": "mobile",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Pro iOS",
        "editor_comments": "Client-side VeChain NFC-chip Scanner.",
        "editor_languages": ["english", "chinese"],
        "job_status":null
    },
    {
        "url": "https://play.google.com/store/apps/details?id=com.vechain.user",
        "category": "tools",
        "platform": "mobile",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Pro Android",
        "editor_comments": "Client-side VeChain NFC-chip Scanner.",
        "editor_languages": ["english", "chinese"],
        "job_status":null
    },
    {
        "url": "env.vechain.org",
        "category": "tools",
        "platform": "desktop",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Sync",
        "editor_comments": "Desktop wallet to transfer funds, view dApps. (Mac, Windows, Linux)",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://chrome.google.com/webstore/detail/vechain-price-checker/ojopeinoooepnfnmifmmjebccpnjamea",
        "category": "tools",
        "platform": "desktop",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Price Checker Extension",
        "editor_comments": "Browser extension to view price quickly.  (Chrome, Firefox)",
        "editor_languages": ["english", "chinese"],
        "job_status":null
    },
    {
        "url": "https://docs.vechain.org/",
        "category": "docs",
        "platform": "website",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Documentation Center",
        "editor_comments": "Developer resources for docs, tutorials and knowledge.",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://docs.vechain.org/connex/intro.html",
        "category": "docs",
        "platform": "website",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Connex",
        "editor_comments": "Connex API documentation. The standard way to connect to the VeChain network.",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://github.com/vechain/vips/",
        "category": "docs",
        "platform": "github",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VIPs",
        "editor_comments": "\"VeChain Improvement Proposals\", where new milestones are planned and discussed.",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://medium.com/@abyteahead/",
        "category": "docs",
        "platform": "medium",
        "run_by_official": false,
        "organization": false,
        "platform_identifier": "abyteahead",
        "personal_account": true,
        "editor_title": "A Byte Ahead Medium",
        "editor_comments": "Tutorials on building apps on VeChain. Explains new features and how-to.",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://bbs.vechainworld.io/",
        "category": "chats",
        "platform": "website",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Discussion Forum",
        "editor_comments": "Announcements, AMA sessions and new developments.",
        "editor_languages": ["english", "chinese"],
        "job_status":null
    },
    {
        "url": "https://www.vechain.org/foundation-grant/",
        "category": "website",
        "platform": "website",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Grant",
        "editor_comments": "Grants to support small start-ups on VeChain.",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://www.vechain.org/bounty-program/",
        "category": "website",
        "platform": "website",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Bounty",
        "editor_comments": "Earn money by building tools for the VeChain Foundation",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://apps.vechain.org/",
        "category": "website",
        "platform": "website",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Dapps Category",
        "editor_comments": "Find interesting 3rd party apps running on VeChain Blockchain.",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://vechain.com/",
        "category": "website",
        "platform": "website",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Vechain.com",
        "editor_comments": "The Official website of VeChain's Blockchain-as-a-Service company.",
        "editor_languages": ["english", "chinese"],
        "job_status":null
    },
    {
        "url": "https://vechain.org/",
        "category": "website",
        "platform": "website",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain.org",
        "editor_comments": "Official website of the VeChain foundation. Includes bounty/grant information and technology advancements.",
        "editor_languages": ["english", "chinese"],
        "job_status":null
    },
    {
        "url": "https://insight.vecha.in",
        "category": "tools",
        "platform": "website",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Insight",
        "editor_comments": "A serverless light-weight VeChain explorer. Search for blocks, transactions and accounts.",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://faucet.vecha.in/",
        "category": "tools",
        "platform": "website",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Faucet",
        "editor_comments": "Provides VET and VTHO on testnet freely. Get some free VET/VTHO when you test dApps!",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://github.com/vechain/picasso",
        "category": "code",
        "platform": "github",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Picasso",
        "editor_comments": "General purpose deterministic identity icon library in svg format, mostly for vechain thor addresses.",
        "editor_languages": ["english"],
        "job_status":null
    },
    {
        "url": "https://github.com/vechain/b32",
        "category": "code",
        "platform": "github",
        "run_by_official": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "B32",
        "editor_comments": "Signature collection of smart contract method & event.",
        "editor_languages": ["english"],
        "job_status":null
    }
]
