categories = {
    "media": {
        display: "Media",
        description: "Official media accounts"
    },
    "websites": {
        display: "Websites",
        description: "Information hubs related to VeChain"
    },
    "people": {
        display: "People",
        description: "Other account to follow"
    },
    "tools": {
        display: "Tools",
        description: "Tools on desktop/mobile"
    },
    "chats": {
        display: "Chats",
        description: "Join the discussions"
    },
    "docs": {
        display: "Docs",
        description: "Code and Libraries"
    },
    "code": {
        display: "Code & SDK",
        description: "Open source projects"
    },
    "projects": {
        display: "Projects",
        description: "Projects running on VeChain"
    }
}

items = [
    {
        "url": "https://medium.com/@vechainofficial",
        "category": "media",
        "platform": "medium",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": "vechainofficial",
        "personal_account": false,
        "editor_comments": "Official account with important updates from the Vechain Foundation.",
        "editor_title": "VeChain Medium",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://twitter.com/vechainofficial",
        "category": "media",
        "platform": "twitter",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": "vechainofficial",
        "personal_account": false,
        "editor_comments": "Official VeChain Twitter account.",
        "editor_title": "VeChain Twitter",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://twitter.com/vechaindev",
        "category": "media",
        "platform": "twitter",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": "vechaindev",
        "personal_account": false,
        "editor_comments": "Developer related news, updates on new technology advancements, tutorials, and milestone releases.",
        "editor_title": "VeChainDev Twitter",
        "editor_languages": ["english"],
        "job_status": null
    },

    {
        "url": "https://weibo.com/u/6353774918",
        "category": "media",
        "platform": "weibo",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": "6353774918",
        "personal_account": false,
        "editor_title": "VeChain Weibo",
        "editor_comments": "The Chinese language VeChain Foundation channel on Weibo.",
        "editor_languages": ["chinese"],
        "job_status": null
    },
    {
        "url": "https://weibo.com/u/6306565418",
        "category": "media",
        "platform": "weibo",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": "6306565418",
        "personal_account": false,
        "editor_title": "VeChain Fans Weibo",
        "editor_comments": "Chinese fans discussion on Weibo.",
        "editor_languages": ["chinese"],
        "job_status": null
    },
    {
        "url": "https://twitter.com/VeChainStats",
        "category": "media",
        "platform": "twitter",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": "VeChainStats",
        "personal_account": false,
        "editor_title": "VechainStats",
        "editor_comments": "Updates from VeChainStats.com, a powerful community block explorer and analytics tool.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://twitter.com/VechainThorCom",
        "category": "media",
        "platform": "twitter",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": "VechainThorCom",
        "personal_account": false,
        "editor_title": "VechainThorCom",
        "editor_comments": "Community Twitter of VeChain.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://vechain101.com/",
        "category": "websites",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain101.com",
        "editor_comments": "Unofficial news and analysis from community editors.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://twitter.com/vechainthorscan",
        "category": "media",
        "platform": "twitter",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": "vechainthorscan",
        "personal_account": false,
        "editor_title": "VechainThorScan",
        "editor_comments": "Updates from a community VeChain explorer with an elegant UI.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://twitter.com/sunshinelu24",
        "category": "people",
        "platform": "twitter",
        "run_by_vechain": false,
        "organization": false,
        "platform_identifier": "sunshinelu24",
        "personal_account": true,
        "editor_title": "Sunny",
        "editor_comments": "CEO of VeChain.",
        "editor_languages": ["english"],
        "job_status": "vechain_team"
    },
    {
        "url": "https://twitter.com/kfeng027",
        "category": "people",
        "platform": "twitter",
        "run_by_vechain": false,
        "organization": false,
        "platform_identifier": "kfeng027",
        "personal_account": true,
        "editor_title": "Kevin",
        "editor_comments": "COO of VeChain.",
        "editor_languages": ["english"],
        "job_status": "vechain_team"
    },
    {
        "url": "https://twitter.com/qian_bin_cola_t",
        "category": "people",
        "platform": "twitter",
        "run_by_vechain": false,
        "organization": false,
        "platform_identifier": "qian_bin_cola_t",
        "personal_account": true,
        "editor_title": "Qian Bin",
        "editor_comments": "Core VeChainThor blockchain dev.",
        "editor_languages": ["english"],
        "job_status": "vechain_team"
    },
    {
        "url": "https://twitter.com/BenYorke",
        "category": "people",
        "platform": "twitter",
        "run_by_vechain": false,
        "organization": false,
        "platform_identifier": "BenYorke",
        "personal_account": true,
        "editor_title": "Ben Yorke",
        "editor_comments": "Editor of VeChain101, and Analyst of Cointelegraph Consulting.",
        "editor_languages": ["english"],
        "job_status": "community_member"
    },
    {
        "url": "https://twitter.com/Sarah_Nabaa",
        "category": "people",
        "platform": "twitter",
        "run_by_vechain": false,
        "organization": false,
        "platform_identifier": "Sarah_Nabaa",
        "personal_account": true,
        "editor_title": "Sarah Nabaa",
        "editor_comments": "Head of VeChain Southeast Asia & Australia.",
        "editor_languages": ["english"],
        "job_status": "vechain_team"
    },
    {
        "url": "https://twitter.com/jeromegrilleres",
        "category": "people",
        "platform": "twitter",
        "run_by_vechain": false,
        "organization": false,
        "platform_identifier": "jeromegrilleres",
        "personal_account": true,
        "editor_title": "Jérôme Grillères",
        "editor_comments": "VeChain EU office GM.",
        "editor_languages": ["english"],
        "job_status": "vechain_team"
    },
    {
        "url": "https://twitter.com/liboliqi",
        "category": "people",
        "platform": "twitter",
        "run_by_vechain": false,
        "organization": false,
        "platform_identifier": "liboliqi",
        "personal_account": true,
        "editor_title": "Tony",
        "editor_comments": "Core VeChainThor blockchain dev.",
        "editor_languages": ["english"],
        "job_status": "vechain_team"
    },
    {
        "url": "https://twitter.com/tahpot",
        "category": "people",
        "platform": "twitter",
        "run_by_vechain": false,
        "organization": false,
        "platform_identifier": "tahpot",
        "personal_account": true,
        "editor_title": "Chris",
        "editor_comments": "Founder of Verida.",
        "editor_languages": ["english"],
        "job_status": "community_member"
    },
    {
        "url": "https://twitter.com/Raleigh_CA",
        "category": "people",
        "platform": "twitter",
        "run_by_vechain": false,
        "organization": false,
        "platform_identifier": "Raleigh_CA",
        "personal_account": true,
        "editor_title": "Kenneth Ashley",
        "editor_comments": "Community Developer.",
        "editor_languages": ["english"],
        "job_status": "community_member"
    },
    {
        "url": "https://twitter.com/jasonrockwood",
        "category": "people",
        "platform": "twitter",
        "run_by_vechain": false,
        "organization": false,
        "platform_identifier": "jasonrockwood",
        "personal_account": true,
        "editor_title": "Jason Rockwood",
        "editor_comments": "Head of VeChain North America.",
        "editor_languages": ["english"],
        "job_status": "vechain_team"
    },
    {
        "url": "https://twitter.com/rgrottola",
        "category": "people",
        "platform": "twitter",
        "run_by_vechain": false,
        "organization": false,
        "platform_identifier": "rgrottola",
        "personal_account": true,
        "editor_title": "Renato Grottola",
        "editor_comments": "DNV GL's Global Head of Digital Assurance and Supply Chain, VeChain Steering Community Member.",
        "editor_languages": ["english"],
        "job_status": "third_party"
    },
    {
        "url": "https://twitter.com/PeterZh47977516",
        "category": "people",
        "platform": "twitter",
        "run_by_vechain": false,
        "organization": false,
        "platform_identifier": "PeterZh47977516",
        "personal_account": true,
        "editor_title": "Dr. Peter Zhou",
        "editor_comments": "VeChain Chief Scientist.",
        "editor_languages": ["english"],
        "job_status": "vechain_team"
    },
    {
        "url": "https://twitter.com/creamethod",
        "category": "people",
        "platform": "twitter",
        "run_by_vechain": false,
        "organization": false,
        "platform_identifier": "creamethod",
        "personal_account": true,
        "editor_title": "Cream",
        "editor_comments": "Incubator and strategic VeChain partner.",
        "editor_languages": ["english"],
        "job_status": "third_party"
    },
    {
        "url": "https://twitter.com/MiRei83_",
        "category": "people",
        "platform": "twitter",
        "run_by_vechain": false,
        "organization": false,
        "platform_identifier": "MiRei83_",
        "personal_account": true,
        "editor_title": "Mirei",
        "editor_comments": "Community Dev and founder of VeBlocks.net.",
        "editor_languages": ["english"],
        "job_status": "community_member"
    },
    {
        "url": "https://twitter.com/veriartivra",
        "category": "people",
        "platform": "twitter",
        "run_by_vechain": false,
        "organization": false,
        "platform_identifier": "veriartivra",
        "personal_account": true,
        "editor_title": "Jamie",
        "editor_comments": "CEO of VeriArti. A VeChain eco-system project.",
        "editor_languages": ["english"],
        "job_status": "third_party"
    },
    {
        "url": "https://twitter.com/d_inderias",
        "category": "people",
        "platform": "twitter",
        "run_by_vechain": false,
        "organization": false,
        "platform_identifier": "d_inderias",
        "personal_account": true,
        "editor_title": "David Inderias",
        "editor_comments": "CEO of freshsupplyco.com",
        "editor_languages": ["english"],
        "job_status": "third_party"
    },
    {
        "url": "https://twitter.com/abyteahead",
        "category": "people",
        "platform": "twitter",
        "run_by_vechain": false,
        "organization": false,
        "platform_identifier": "abyteahead",
        "personal_account": true,
        "editor_title": "A Byte Ahead",
        "editor_comments": "VeChain Core dev and the writer of tutorials and apps.",
        "editor_languages": ["english"],
        "job_status": "vechain_team"
    },
    {
        "url": "https://www.reddit.com/r/Vechain/",
        "category": "chats",
        "platform": "reddit",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": "Vechain",
        "personal_account": false,
        "editor_title": "VeChain Reddit",
        "editor_comments": "General discussion channel on Reddit.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "env.vechain.org",
        "category": "tools",
        "platform": "desktop",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Sync",
        "editor_comments": "Transfer funds, view dApps and manage wallets on Mac, Windows, Linux. Supports Ledger Nano S and X.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://explore.vechain.org/",
        "category": "tools",
        "platform": "website",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Explorer",
        "editor_comments": "Fast and reliable official block explorer.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "http://vechainstats.com/",
        "category": "tools",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VechainStats",
        "editor_comments": "Community VeChain explorer with rich functionalities.",
        "editor_languages": ["english", "chinese",],
        "job_status": null
    },
    {
        "url": "https://visuals.veblocks.net",
        "category": "tools",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeBlocks.net",
        "editor_comments": "Community mainnet activity monitor.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://wallu.vechainstats.com",
        "category": "tools",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Wallü",
        "editor_comments": "Wallet management and monitoring tool.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://www.vexplorer.io",
        "category": "tools",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Vexplorer",
        "editor_comments": "Community VeChain block explorer.",
        "editor_languages": ["english", "chinese", ""],
        "job_status": null
    },
    {
        "url": "https://vechainthorscan.com/",
        "category": "tools",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VechainThorScan",
        "editor_comments": "Community VeChain explorer with an elegant UI.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://vechaininsider.com/",
        "category": "websites",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Insider",
        "editor_comments": "Community run VeChain News.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://cointelegraph.com/consulting/vechain",
        "category": "websites",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "CoinTelegraph Consulting Vendor Page",
        "editor_comments": "Case studies and technology review.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://t.me/VeChainDevCommunity",
        "category": "chats",
        "platform": "telegram",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": "VeChainDevCommunity",
        "personal_account": false,
        "editor_title": "Developers' Chat",
        "editor_comments": "Huge community developers' chat on coding. Go make some friends there!",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://t.me/vechain_official_CN",
        "category": "chats",
        "platform": "telegram",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": "vechain_official_CN",
        "personal_account": false,
        "editor_title": "Chinese Telegram",
        "editor_comments": "Traders, announcements and price discussions in Chinese.",
        "editor_languages": ["chinese"],
        "job_status": null
    },
    {
        "url": "https://t.me/vechain_official_en",
        "category": "chats",
        "platform": "telegram",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": "vechain_official_en",
        "personal_account": false,
        "editor_title": "English Telegram",
        "editor_comments": "Traders, announcements and price discussions in English.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://t.me/VeChainOfficialSeriousDiscussion",
        "category": "chats",
        "platform": "telegram",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": "VeChainOfficialSeriousDiscussion",
        "personal_account": false,
        "editor_title": "VeChain Official Serious Discussion",
        "editor_comments": "Serious VeChain discussion free of memes, gifs and price discussion.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://t.me/vechainthorscan",
        "category": "chats",
        "platform": "telegram",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": "vechainthorscan",
        "personal_account": false,
        "editor_title": "Vechainthorscan Devs",
        "editor_comments": "Developers' discussion, bug fix, feature request of vechainthorscan.com",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://t.me/vechainwallet",
        "category": "chats",
        "platform": "telegram",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": "vechainwallet",
        "personal_account": false,
        "editor_title": "Community Browser Extension",
        "editor_comments": "Discussion of a newly made Chrome browser wallet extension.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://t.me/VeriArti",
        "category": "chats",
        "platform": "telegram",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": "VeriArti",
        "personal_account": false,
        "editor_title": "VeriArti Offical",
        "editor_comments": "General topics about VeriArti - Unique digital art tokens (NFTs) on VeChain.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://github.com/vechain/",
        "category": "code",
        "platform": "github",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Github",
        "editor_comments": "Main Source code of VeChain blockchain, tools, and libraries.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://github.com/vechain/token-registry",
        "category": "code",
        "platform": "github",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Token Registry",
        "editor_comments": "Tokens residing on VeChain. You can submit one by pull request.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://github.com/vechain/app-hub",
        "category": "code",
        "platform": "github",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "App Hub",
        "editor_comments": "3rd party dApps appearing in Sync. You can submit one by pull request.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://github.com/vechain/thor-devkit.js",
        "category": "code",
        "platform": "github",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Thor Devkit",
        "editor_comments": "JavaScript SDK library. Wallets generation, transaction assembling.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://apps.apple.com/fi/app/vechainthor/id1397679485",
        "category": "tools",
        "platform": "mobile",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Wallet for iOS",
        "editor_comments": "Official mobile wallet and dApp browser.",
        "editor_languages": ["english", "chinese"],
        "job_status": null
    },
    {
        "url": "https://play.google.com/store/apps/details?id=com.vechain.wallet",
        "category": "tools",
        "platform": "mobile",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Wallet for Android",
        "editor_comments": "Official mobile wallet and dApp browser.",
        "editor_languages": ["english", "chinese"],
        "job_status": null
    },
    {
        "url": "https://apps.apple.com/fi/app/vechain-pro/id1335906787",
        "category": "tools",
        "platform": "mobile",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Pro iOS",
        "editor_comments": "Client-side VeChain NFC-chip Scanner.",
        "editor_languages": ["english", "chinese"],
        "job_status": null
    },
    {
        "url": "https://play.google.com/store/apps/details?id=com.vechain.user",
        "category": "tools",
        "platform": "mobile",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Pro Android",
        "editor_comments": "Client-side VeChain NFC-chip Scanner.",
        "editor_languages": ["english", "chinese"],
        "job_status": null
    },
    {
        "url": "https://manager.vechainstats.com",
        "category": "tools",
        "platform": "desktop",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Node Manager",
        "editor_comments": "A third party node manager from the makers of VeChainStats.com",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://chrome.google.com/webstore/detail/vechain-price-checker/ojopeinoooepnfnmifmmjebccpnjamea",
        "category": "tools",
        "platform": "desktop",
        "run_by_vechain": false,
        "organization": false,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Price Checker Extension",
        "editor_comments": "Browser extension to view price quickly on Chrome and Firefox.",
        "editor_languages": ["english", "chinese"],
        "job_status": null
    },
    {
        "url": "https://connex.vexchange.io/",
        "category": "tools",
        "platform": "desktop",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Vexchange",
        "editor_comments": "Decentralized exchange powered by smart contracts.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://laalaguer.github.io/VeChain-Address/",
        "category": "tools",
        "platform": "desktop",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Address Generator",
        "editor_comments": "Simple paper wallet generator on in your browser. For testing purpose only.",
        "editor_languages": ["english", "chinese"],
        "job_status": null
    },
    {
        "url": "https://laalaguer.github.io/vechain-token-transfer/",
        "category": "tools",
        "platform": "desktop",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Tokens",
        "editor_comments": "Supports more than 10+ tokens on VeChain. Allows batch transfer with CSV file.",
        "editor_languages": ["english", "chinese"],
        "job_status": null
    },
    {
        "url": "https://tokens.vecha.in/#/wallets",
        "category": "tools",
        "platform": "desktop",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "My Tokens",
        "editor_comments": "Transfer of tokens made easy.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://docs.vechain.org/",
        "category": "docs",
        "platform": "website",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Learning Center",
        "editor_comments": "Developer resources for docs, tutorials and knowledge.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://docs.vechain.org/connex/intro.html",
        "category": "docs",
        "platform": "website",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Connex",
        "editor_comments": "Connex API documentation. The standard way to connect to the VeChain network.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://github.com/vechain/vips/",
        "category": "docs",
        "platform": "github",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VIPs",
        "editor_comments": "\"VeChain Improvement Proposals\", where new milestones are planned and discussed.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://medium.com/@abyteahead/",
        "category": "docs",
        "platform": "medium",
        "run_by_vechain": false,
        "organization": false,
        "platform_identifier": "abyteahead",
        "personal_account": true,
        "editor_title": "A Byte Ahead Medium",
        "editor_comments": "Tutorials on building apps on VeChain. Explains new features and how-to.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://bbs.vechainworld.io/",
        "category": "chats",
        "platform": "website",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Discussion Forum",
        "editor_comments": "Announcements, AMA sessions and new developments.",
        "editor_languages": ["english", "chinese"],
        "job_status": null
    },
    {
        "url": "https://www.vechain.org/foundation-grant/",
        "category": "websites",
        "platform": "website",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Grant",
        "editor_comments": "Grants to support small start-ups on VeChain.",
        "editor_languages": ["english"],
        "job_status": null
    }, {
        "url": "http://www.vechainuniverse.com",
        "category": "websites",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Universe",
        "editor_comments": "Mainnet activity visualizer with firework display.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://www.vechain.org/bounty-program/",
        "category": "websites",
        "platform": "website",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "VeChain Bounty",
        "editor_comments": "Earn money by building tools for the VeChain Foundation",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://apps.vechain.org/",
        "category": "websites",
        "platform": "website",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Dapps Category",
        "editor_comments": "Find interesting 3rd party apps running on VeChain Blockchain.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://vechain.com/",
        "category": "websites",
        "platform": "website",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Vechain.com",
        "editor_comments": "The Official website of VeChain's Blockchain-as-a-Service company.",
        "editor_languages": ["english", "chinese"],
        "job_status": null
    },
    {
        "url": "https://vechain.org/",
        "category": "websites",
        "platform": "website",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Vechain.org",
        "editor_comments": "Official website of the VeChain foundation. Includes bounty information and technology advancements.",
        "editor_languages": ["english", "chinese"],
        "job_status": null
    },
    {
        "url": "https://insight.vecha.in",
        "category": "tools",
        "platform": "website",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Insight",
        "editor_comments": "A serverless light-weight VeChain explorer. Search for blocks, transactions and accounts.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://www.play2048x.com",
        "category": "tools",
        "platform": "website",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "2048",
        "editor_comments": "A classic mobile game that uses VET/VTHO as a jackpot reward.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://faucet.vecha.in/",
        "category": "tools",
        "platform": "website",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Faucet",
        "editor_comments": "Provides VET and VTHO on testnet freely. Get some free VET/VTHO when you test dApps!",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://github.com/vechain/picasso",
        "category": "code",
        "platform": "github",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Picasso",
        "editor_comments": "General purpose icon library in svg format, for VechainThor wallet addresses.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://github.com/vechain/wallet-Android-sdk",
        "category": "code",
        "platform": "github",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Android SDK",
        "editor_comments": "Interact with VeChain, create and manage wallets, compatible with Connex standard.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://github.com/vechain/wallet-iOS-sdk",
        "category": "code",
        "platform": "github",
        "run_by_vechain": true,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "iOS SDK",
        "editor_comments": "Interact with VeChain, create and manage wallets, compatible with Connex standard.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://www.dnvgl.com/mystory/index.html",
        "category": "projects",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "My Story™ by DNV GL",
        "editor_comments": "Blockchain powered Digital Assurance.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://freshsupplyco.com",
        "category": "projects",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Fresh Supply Co.",
        "editor_comments": "Food Company that offers provenance/traceability for ag exports.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://en.foodgates.com",
        "category": "projects",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Foodgates",
        "editor_comments": "B2B food traceability platform between France and China.",
        "editor_languages": ["english", "chinese"],
        "job_status": null
    },
    {
        "url": "https://realitems.io/",
        "category": "projects",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Real Items",
        "editor_comments": "Product authenticity, supply-chain transparency and consumer protection.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://8hoursfoundation.org",
        "category": "projects",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "8 Hours Foundation",
        "editor_comments": "A complete NFT and cryptocurrency ecosystem for the Play Table, the world's first blockchain-enabled tabletop game console.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://jur.io/",
        "category": "projects",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Jur",
        "editor_comments": "A decentralized legaltech ecosystem with online dispute resolution and smart legal contracts.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://oceanex.pro",
        "category": "projects",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "OceanEx",
        "editor_comments": "A cryptocurrency exchange partnered with VeChain.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://safehaven.io",
        "category": "projects",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Safe Haven",
        "editor_comments": "A financial tool, asset management platform, and digital inheritance solution.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://www.plair.life",
        "category": "projects",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Plair",
        "editor_comments": "A decentralized gaming ecosystem.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://playdecent.gg",
        "category": "projects",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "PlayDecent",
        "editor_comments": "Gaming platform to stake and win tokens.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://www.cecilalliance.com",
        "category": "projects",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "Cecil Alliance",
        "editor_comments": "The Internet of Animals: Empowering animal data through blockchain.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://hacken.ai",
        "category": "projects",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "HackenAI",
        "editor_comments": "A cybersecurity suit for blockchain.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://www.workpi.io",
        "category": "projects",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "WorkPi",
        "editor_comments": "Human Resource Management and shared job economy platform.",
        "editor_languages": ["english"],
        "job_status": null
    },
    {
        "url": "https://snkcoin.org",
        "category": "projects",
        "platform": "website",
        "run_by_vechain": false,
        "organization": true,
        "platform_identifier": null,
        "personal_account": false,
        "editor_title": "SNKr",
        "editor_comments": "A decentralized streetwear ecosystem.",
        "editor_languages": ["english"],
        "job_status": null
    },
]
